### ISSUE TITLE
Got an error while using npm start command.. 

### ISSUE THREAD

**Issue by Sravan921** [wardbell/code-with-us-angular-quickstart#4] opened 2017-02-13 06:56 UTC
node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.

**Comment by cseils** [comment] 2017-02-14 05:48
The problem is caused by the latest jasmine type definition requiring typescript 2.1
If you update typescript, and then run npm start, it should work

```
npm install typescript@2.1 --save-dev
```

**Comment by johnpapa** [comment] 2017-02-19 19:50
@wardbell and I will look into this, since a few folks have reported it

**Comment by jatinam** [comment] 2017-02-22 01:26
I got the same error. Here is the complete log. The log is attached as a .txt file as well.
As cseils mentioned above after updating typescript it works fine.
npm install typescript@2.1 --save-dev

------------------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\user1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.2.0
3 info using node@v6.9.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle code-with-us-in-ng-2@1.0.0~prestart: code-with-us-in-ng-2@1.0.0
6 silly lifecycle code-with-us-in-ng-2@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle code-with-us-in-ng-2@1.0.0~start: code-with-us-in-ng-2@1.0.0
8 verbose lifecycle code-with-us-in-ng-2@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle code-with-us-in-ng-2@1.0.0~start: PATH: C:\Users\user1\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Work\Learn\PS\code-with-us-angular-quickstart-master\node_modules\.bin;C:\Utils\Bin\cmder\bin;C:\Utils\Bin\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Utils\Bin\cmder\vendor\conemu-maximus5;C:\Utils\Bin\cmder\vendor\conemu-maximus5\ConEmu;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\user1\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\cmd;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\PuTTY\;C:\Users\user1\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2\bin;C:\Users\user1\.dnx\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\user1\AppData\Local\Microsoft\WindowsApps;C:\Users\user1\AppData\Roaming\npm;C:\Users\user1\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\share\vim\vim74;C:\Utils\Bin\cmder\
10 verbose lifecycle code-with-us-in-ng-2@1.0.0~start: CWD: C:\Work\Learn\PS\code-with-us-angular-quickstart-master
11 silly lifecycle code-with-us-in-ng-2@1.0.0~start: Args: [ '/d /s /c', 'tsc && concurrently "tsc -w" "lite-server" ' ]
12 silly lifecycle code-with-us-in-ng-2@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle code-with-us-in-ng-2@1.0.0~start: Failed to exec start script
14 verbose stack Error: code-with-us-in-ng-2@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\user1\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\user1\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid code-with-us-in-ng-2@1.0.0
16 verbose cwd C:\Work\Learn\PS\code-with-us-angular-quickstart-master
17 error Windows_NT 10.0.15031
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.2
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error code-with-us-in-ng-2@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
23 error Exit status 2
24 error Failed at the code-with-us-in-ng-2@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the code-with-us-in-ng-2 package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     tsc && concurrently "tsc -w" "lite-server"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs code-with-us-in-ng-2
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls code-with-us-in-ng-2
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]

[2017-02-22T01_22_52_210Z-debug.txt](https://github.com/wardbell/code-with-us-angular-quickstart/files/791990/2017-02-22T01_22_52_210Z-debug.txt)

**Comment by wardbell** [comment] 2017-02-22 04:11
Thanks for identifying the root cause in `@types/jasmine`.  It is very disappointing that they introduced the breaking changes.

The solution is not to bump to TS 2.1 as suggested here. Angular won't support TS 2.1 until v.4 (very very soon but not today). It works for v.2 ... unless you try the AOT compiler. So we're sticking with TS 2.0.x for now.

I'm correcting the github repo to pin the versions for these two libraries that are known to work today. They match what we're doing in Angular today.

1)  "@types/jasmine": "2.5.36"
2)  "rxjs": "5.0.1"

I'm closing because I believe the essential problem has been fixed as of commit e8fb8d1. Let me know if it isn't. Again, much obliged for your analysis!

**Closed as completed by wardbell** 2017-02-22 04:11 UTC
